import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const root = fileURLToPath(new URL('.', import.meta.url));

// The page is a single 1920x1080 canvas; audio/ (music.mp3 generated by audio/music.py) is served at /.
export default defineConfig({
  root,
  publicDir: path.join(root, 'audio'),
  server: { host: '127.0.0.1', port: 5174, open: false },
  build: { outDir: path.join(root, 'dist'), emptyOutDir: true, target: 'es2022', sourcemap: false, copyPublicDir: false },
});
